name: Generate documentation

on:
  push:
    branches: [ master ]
    paths:
    - 'ontologies/audioset.rdf'

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ontospy[FULL]

    - name: Generate docs
      run: |
        ontospy gendocs -o docs/summary --type 1 --nobrowser ontologies/audioset.rdf
        ontospy gendocs -o docs/browse --type 2 --nobrowser ontologies/audioset.rdf
        ontospy gendocs -o docs/classtree --type 4 --nobrowser ontologies/audioset.rdf
        ontospy gendocs -o docs/graph --type 10 --nobrowser ontologies/audioset.rdf

    - name: Hotfix graph nodes sizes
      run: |
        find docs/graph/index.html -type f -exec sed -i "s/minNodeSize: 1,/minNodeSize: 2,/g" {} +
        find docs/graph/index.html -type f -exec sed -i "s/maxNodeSize: 30,/maxNodeSize: 24,/g" {} +

    - name: Commit and push
      run: |
        git config --global user.name 'Vincent Emonet'
        git config --global user.email 'vincent.emonet@maastrichtuniversity.nl'
        git add -A && git commit -m "Automatically generate documentation from AudioSet OWL ontology file using Ontospy gendocs."
        git push
    
